# -*- coding: utf-8 -*-
"""YANG RIZKAAAAAAAAAAAAAa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdFk_CgxMD-Mt8iW1jazSjIWCbLomhCZ

IMPORT LIBRARY
"""

import pandas as pd
import numpy as np
import joblib
import warnings
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, cross_validate
from sklearn.metrics import (
    classification_report, accuracy_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils.class_weight import compute_class_weight
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

import shap

warnings.filterwarnings('ignore')

plt.rcParams.update({
    'figure.dpi': 150,
    'font.size': 11,
    'axes.titlesize': 13,
    'axes.labelsize': 11,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
})
LABEL_NAMES  = ['Rendah', 'Sedang', 'Tinggi']
COLOR_RISIKO = ['#2ecc71', '#f39c12', '#e74c3c']

"""# FASE 1: DATA UNDERSTANDING

LOAD DATA
"""

from google.colab import files
uploaded = files.upload()   # pilih file data_gabungan_2019_2024.csv

import io
df_raw = pd.read_csv(io.BytesIO(list(uploaded.values())[0]))
print("Data mentah shape:", df_raw.shape)
print("Kolom:", list(df_raw.columns))
print("Tahun unik di data mentah:", sorted(df_raw['tahun'].unique()))

"""HAPUS DUPLIKAT"""

df = df_raw.drop_duplicates()
print("Duplikat dihapus. Shape:", df.shape)
print("Tahun unik setelah hapus duplikat:", sorted(df['tahun'].unique()))

"""AGREGASI (GROUPBY MEDIAN)"""

df['tahun'] = pd.to_numeric(df['tahun'], errors='coerce')

group_cols = ['kode_kabupaten_kota', 'nama_kabupaten_kota', 'tahun']
numeric_cols = df.select_dtypes(include=np.number).columns.difference(group_cols)

df = df.groupby(group_cols)[numeric_cols].median().reset_index()
df['nama_provinsi'] = 'JAWA BARAT'
df['kode_provinsi'] = 32

print("Agregasi selesai. Shape:", df.shape)
print("Tahun unik setelah agregasi:", sorted(df['tahun'].unique()))

"""HANDLING MISSING VALUE (INF, NaN)
python

"""

df = df.replace([np.inf, -np.inf], np.nan)
df = df.fillna(df.median(numeric_only=True))
print("Missing value diisi. Shape:", df.shape)
print("Rentang tahun        :", df['tahun'].min(), "–", df['tahun'].max())
print("Jumlah kab/kota      :", df['nama_kabupaten_kota'].nunique())
print("Tahun unik           :", sorted(df['tahun'].unique()))

"""FEATURE ENGINEERING"""

# Setelah df terbentuk (setelah agregasi dan fillna),
# pastikan kolom memiliki nama yang benar.

# Cek kolom yang ada
existing_cols = df.columns.tolist()
print("Kolom yang tersedia:", existing_cols)

# Mapping kolom jika nama berbeda
column_mapping = {
    'persentase_sanitasi_layak': ['persentase_sanitasi_layak', 'persentase_rumah_tangga_memiliki_akses_terhadap_sanitasi_layak', 'sanitasi_layak'],
    'persentase_air_minum_layak': ['persentase_air_minum_layak', 'persentase_rumah_tangga_memiliki_akses_terhadap_air_minum_layak', 'air_minum_layak'],
    'persentase_rumah_layak_huni': ['persentase_rumah_layak_huni', 'persentase_rumah_tangga_menempati_rumah_layak_huni', 'rumah_layak_huni'],
    'persentase_penduduk_miskin': ['persentase_penduduk_miskin', 'persentase_penduduk_miskin', 'miskin'],
    'jumlah_faskes': ['jumlah_faskes', 'jumlah_fasilitas_kesehatan'],
    'jumlah_nakesmas': ['jumlah_nakesmas', 'jml_tenaga_kesehatan_msyrkt', 'jumlah_tenaga_kesehatan_masyarakat'],
    'jumlah_penduduk': ['jumlah_penduduk'],
    'kepadatan_penduduk': ['kepadatan_penduduk'],
    'pengeluaran_per_kapita': ['pengeluaran_per_kapita'],
    'indeks_pembangunan_manusia': ['indeks_pembangunan_manusia', 'ipm']
}

# Rename kolom berdasarkan mapping
for target, alternatives in column_mapping.items():
    found = False
    for alt in alternatives:
        if alt in df.columns:
            if alt != target:
                df.rename(columns={alt: target}, inplace=True)
            found = True
            break
    if not found:
        print(f"Peringatan: Kolom untuk '{target}' tidak ditemukan. Coba periksa data.")

# Setelah rename, lanjutkan ke feature engineering

"""Membuat risk_proxy"""

# Tampilkan semua nama kolom saat ini
print("Kolom yang tersedia:", df.columns.tolist())

# Mapping manual dari nama asli (yang mungkin muncul) ke nama baku
rename_mapping = {}

# Cek satu per satu kolom yang diperlukan
required_cols = [
    'persentase_penduduk_miskin',
    'indeks_pembangunan_manusia'
]

for col in required_cols:
    # Cari kolom yang mengandung kata kunci
    found = None
    for col_name in df.columns:
        if col.lower() in col_name.lower() or col_name.lower() in col.lower():
            found = col_name
            break
    if found and found != col:
        rename_mapping[found] = col
        print(f"Renaming: '{found}' → '{col}'")
    elif found == col:
        print(f"Kolom '{col}' sudah ada.")
    else:
        print(f"⚠️ WARNING: Kolom untuk '{col}' tidak ditemukan!")

# Terapkan rename
if rename_mapping:
    df.rename(columns=rename_mapping, inplace=True)
    print("Setelah rename, kolom:", df.columns.tolist())

# ===== PASTIKAN FITUR TURUNAN TERSEDIA =====
if 'basic_service_index' not in df.columns:
    df["basic_service_index"] = (
        df["persentase_sanitasi_layak"] +
        df["persentase_air_minum_layak"] +
        df["persentase_rumah_layak_huni"]
    ) / 3
if 'faskes_ratio' not in df.columns:
    df["faskes_ratio"] = df["jumlah_faskes"] / (df["jumlah_penduduk"] / 1000 + 1)
if 'poverty_density' not in df.columns:
    df["poverty_density"] = df["persentase_penduduk_miskin"] * df["kepadatan_penduduk"]

features = [
    "basic_service_index",
    "faskes_ratio",
    "poverty_density",
    "pengeluaran_per_kapita",
    "kepadatan_penduduk",
]

"""DETEKSI OUTLIER (IQR)"""

n_feat = len(features)
ncols  = 3
nrows  = int(np.ceil(n_feat / ncols))
fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * 4, nrows * 4))
axes = axes.flatten()

print("\n=== RINGKASAN OUTLIER (IQR) ===")
outlier_rows = []
for i, col in enumerate(features):
    ax = axes[i]
    ax.boxplot(df[col].dropna(), patch_artist=True,
               boxprops=dict(facecolor='#AED6F1', color='#2980B9'),
               medianprops=dict(color='red', linewidth=2),
               whiskerprops=dict(color='#2980B9'),
               capprops=dict(color='#2980B9'),
               flierprops=dict(marker='o', color='orange',
                               markerfacecolor='orange', markersize=5))
    Q1  = df[col].quantile(0.25)
    Q3  = df[col].quantile(0.75)
    IQR = Q3 - Q1
    n_out = int(((df[col] < Q1 - 1.5*IQR) | (df[col] > Q3 + 1.5*IQR)).sum())
    ax.set_title(f"{col}\n({n_out} outlier)", fontsize=9)
    ax.set_xticks([])
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(
        lambda x, _: f'{x:,.0f}' if abs(x) > 1000 else f'{x:.2f}'))
    outlier_rows.append({'Fitur': col, 'Q1': round(Q1, 4),
                         'Q3': round(Q3, 4), 'IQR': round(IQR, 4),
                         'Jumlah Outlier': n_out})

for j in range(n_feat, len(axes)):
    axes[j].set_visible(False)

fig.suptitle("Boxplot Deteksi Outlier Per Fitur (Data Asli)", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig("boxplot_outlier.png", dpi=150, bbox_inches='tight')
plt.show()
print(pd.DataFrame(outlier_rows).to_string(index=False))

# ===== PASTIKAN SEMUA FITUR TERSEDIA =====
# Buat fitur turunan jika belum ada
if 'basic_service_index' not in df.columns:
    df["basic_service_index"] = (
        df["persentase_sanitasi_layak"] +
        df["persentase_air_minum_layak"] +
        df["persentase_rumah_layak_huni"]
    ) / 3
if 'faskes_ratio' not in df.columns:
    df["faskes_ratio"] = df["jumlah_faskes"] / (df["jumlah_penduduk"] / 1000 + 1)
if 'poverty_density' not in df.columns:
    df["poverty_density"] = df["persentase_penduduk_miskin"] * df["kepadatan_penduduk"]

# Buat risk_proxy jika belum ada
if 'risk_proxy' not in df.columns:
    df["risk_proxy"] = (
        df["persentase_penduduk_miskin"] +
        (100 - df["indeks_pembangunan_manusia"])
    ) / 2

# Definisikan features
features = [
    "basic_service_index",
    "faskes_ratio",
    "poverty_density",
    "pengeluaran_per_kapita",
    "kepadatan_penduduk",
]

"""MATRIKS KORELASI"""

corr_cols = features + ['risk_proxy']
plt.figure(figsize=(10, 8))
corr = df[corr_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool), k=1)
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f',
            linewidths=0.5, mask=mask, vmin=-1, vmax=1,
            annot_kws={"size": 9})
plt.title("Matriks Korelasi Antar Fitur & Risk Proxy (Data Asli)", fontweight='bold')
plt.tight_layout()
plt.savefig("correlation_matrix.png", dpi=150, bbox_inches='tight')
plt.show()

"""# FASE 2: DATA PREPARATION

LABELING DENGAN PERSENTIL P33/P66
"""

train_proxy = df[df['tahun'] <= 2022]['risk_proxy']
P33 = train_proxy.quantile(0.33)
P66 = train_proxy.quantile(0.66)
print(f"\nP33 = {P33:.4f}, P66 = {P66:.4f}")

def label_risiko(x):
    if x <= P33:
        return 0    # Rendah
    elif x >= P66:
        return 2    # Tinggi
    else:
        return 1    # Sedang

df["kategori_risiko"] = df["risk_proxy"].apply(label_risiko)

print("Distribusi kelas seluruh data:")
print(df["kategori_risiko"].value_counts().sort_index()
      .rename({0: 'Rendah', 1: 'Sedang', 2: 'Tinggi'}))

"""VISUALISASI DISTRIBUSI KELAS PER TAHUN"""

fig, ax = plt.subplots(figsize=(10, 4))
pivot = df.groupby(['tahun', 'kategori_risiko']).size().unstack(fill_value=0)
for c in [0, 1, 2]:
    if c not in pivot.columns:
        pivot[c] = 0
pivot = pivot[[0, 1, 2]]
pivot.columns = LABEL_NAMES
pivot.plot(kind='bar', ax=ax, color=COLOR_RISIKO, edgecolor='white', width=0.7)
ax.set_title("Distribusi Kelas Risiko TBC per Tahun")
ax.set_xlabel("Tahun")
ax.set_ylabel("Jumlah Kab/Kota")
ax.legend(title="Risiko")
ax.set_xticklabels(pivot.index, rotation=0)
plt.tight_layout()
plt.savefig("distribusi_kelas_per_tahun.png", dpi=150, bbox_inches='tight')
plt.show()

"""TIME SERIES SPLIT"""

train_df = df[df['tahun'] <= 2022]
val_df   = df[df['tahun'] == 2023]
test_df  = df[df['tahun'] == 2024]

X_train = train_df[features].values
y_train = train_df["kategori_risiko"].values
X_val   = val_df[features].values
y_val   = val_df["kategori_risiko"].values
X_test  = test_df[features].values
y_test  = test_df["kategori_risiko"].values

print(f"\nTrain : {X_train.shape}  |  Val : {X_val.shape}  |  Test : {X_test.shape}")
print("Distribusi kelas train :", np.bincount(y_train))
print("Distribusi kelas val   :", np.bincount(y_val))
print("Distribusi kelas test  :", np.bincount(y_test))

"""NORMALISASI MIN-MAX"""

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

"""SMOTE"""

min_class_count = int(np.bincount(y_train).min())
k_neighbors     = max(1, min(5, min_class_count - 1))
smote           = SMOTE(random_state=42, k_neighbors=k_neighbors)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)
print(f"\nSMOTE k_neighbors = {k_neighbors}")
print("Distribusi kelas setelah SMOTE:", np.bincount(y_train_res))

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
before = pd.Series(y_train).value_counts().sort_index()
after  = pd.Series(y_train_res).value_counts().sort_index()
for ax, counts, title in zip(axes,
                              [before, after],
                              ["Sebelum SMOTE", "Setelah SMOTE"]):
    bars = ax.bar(LABEL_NAMES, counts.values, color=COLOR_RISIKO,
                  edgecolor='white', width=0.5)
    ax.bar_label(bars, padding=3, fontsize=10)
    ax.set_title(title, fontweight='bold')
    ax.set_xlabel("Kelas Risiko")
    ax.set_ylabel("Jumlah Sampel")
    ax.set_ylim(0, max(counts.values) * 1.25)
fig.suptitle("Distribusi Kelas Sebelum dan Setelah SMOTE", fontsize=13)
plt.tight_layout()
plt.savefig("smote_comparison.png", dpi=150, bbox_inches='tight')
plt.show()

"""SAMPLE WEIGHTING"""

classes        = np.unique(y_train_res)
weights        = compute_class_weight(class_weight="balanced",
                                      classes=classes, y=y_train_res)
sample_weights = np.array([weights[int(y)] for y in y_train_res])
print(f"\nBobot kelas: { {LABEL_NAMES[i]: round(w, 4) for i, w in enumerate(weights)} }")

"""HYPERPARAMETER TUNING"""

xgb_base = XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42,
    verbosity=0,
)

# Parameter yang akan dicari
param_dist = {
    'n_estimators'    : [100, 200, 300, 400],
    'max_depth'       : [3, 4, 5, 6, 7],
    'learning_rate'   : [0.01, 0.05, 0.1, 0.15, 0.2],
    'subsample'       : [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'gamma'           : [0, 0.1, 0.2, 0.3],
    'reg_alpha'       : [0, 0.1, 0.5, 1],
    'reg_lambda'      : [1, 1.5, 2, 2.5],
    'min_child_weight': [1, 3, 5],
}

# Validasi silang StratifiedKFold 5 lipatan
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Randomized Search
random_search = RandomizedSearchCV(
    estimator=xgb_base,
    param_distributions=param_dist,
    n_iter=60,
    cv=skf,
    scoring='f1_macro',
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# Proses tuning
random_search.fit(
    X_train_res,
    y_train_res,
    sample_weight=sample_weights
)

# Menampilkan hasil terbaik
best_params = random_search.best_params_

print("\n" + "="*50)
print("BEST HYPERPARAMETERS")
print("="*50)

for param, value in best_params.items():
    print(f"{param:<20}: {value}")

print("="*50)
print(f"Best CV F1-macro     : {random_search.best_score_:.4f}")
print("="*50)

"""TRAINING MODEL"""

model = XGBClassifier(
    **best_params,
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42,
    verbosity=0,
)
model.fit(X_train_res, y_train_res, sample_weight=sample_weights)

"""THRESHOLD TUNING (Health-sensitive)"""

def apply_threshold(proba, t0, t_high):
    preds = []
    for p in proba:
        if p[2] >= t_high:
            preds.append(2)
        elif p[0] >= t0:
            preds.append(0)
        else:
            preds.append(1)
    return np.array(preds)

proba_val   = model.predict_proba(X_val_scaled)
best_score  = -1
best_t0     = 0.50
best_t_high = 0.50

for t_high in np.arange(0.15, 0.72, 0.05):
    for t0 in np.arange(0.30, 0.82, 0.05):
        pred_val = apply_threshold(proba_val, t0, t_high)
        if len(np.unique(pred_val)) < 2:
            continue
        f1_mac  = f1_score(y_val, pred_val, average='macro', zero_division=0)
        cm_val  = confusion_matrix(y_val, pred_val, labels=[0, 1, 2])
        tinggi_total  = cm_val[2].sum()
        recall_tinggi = cm_val[2, 2] / tinggi_total if tinggi_total > 0 else 0
        score = 0.5 * f1_mac + 0.5 * recall_tinggi
        if score > best_score:
            best_score  = score
            best_t0     = t0
            best_t_high = t_high

# Override t_high untuk prioritas sensitivitas kelas Tinggi
best_t_high = 0.20

best_f1 = f1_score(y_val, apply_threshold(proba_val, best_t0, best_t_high),
                   average='macro', zero_division=0)
print(f"\nThreshold final: t_high={best_t_high:.2f} | t0={best_t0:.2f}")
print(f"Validation F1-macro = {best_f1:.4f}")

"""EVALUASI DATA UJI"""

proba_test = model.predict_proba(X_test_scaled)
y_pred     = apply_threshold(proba_test, best_t0, best_t_high)

print("\n=== CLASSIFICATION REPORT XGBoost ===")
print(classification_report(y_test, y_pred,
                             target_names=LABEL_NAMES,
                             zero_division=0))

acc_xgb      = accuracy_score(y_test, y_pred)
f1_macro_xgb = f1_score(y_test, y_pred, average='macro', zero_division=0)
print(f"Akurasi XGBoost  : {acc_xgb * 100:.2f}%")
print(f"Macro F1 XGBoost : {f1_macro_xgb * 100:.2f}%")

"""VALIDASI SILANG 5-FOLD"""

print("\n=== VALIDASI SILANG 5-FOLD (verifikasi konsistensi training) ===")
print("[Catatan] CV dilakukan pada data training post-SMOTE.")
print("[Catatan] Evaluasi generalisasi utama tetap pada test set 2024.\n")

model_cv = XGBClassifier(
    **best_params,
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss',
    use_label_encoder=False,
    random_state=42,
    verbosity=0,
)

cv_skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_results = cross_validate(
    model_cv, X_train_res, y_train_res,
    cv=cv_skf,
    scoring={
        'accuracy' : 'accuracy',
        'f1_macro' : 'f1_macro',
    },
    return_train_score=False,
    n_jobs=-1,
)

cv_acc = cv_results['test_accuracy']
cv_f1  = cv_results['test_f1_macro']

print(f"Akurasi per fold : {[f'{v*100:.1f}%' for v in cv_acc]}")
print(f"F1-macro per fold: {[f'{v*100:.1f}%' for v in cv_f1]}")
print(f"Rata-rata akurasi : {cv_acc.mean()*100:.2f}% ± {cv_acc.std()*100:.2f}%")
print(f"Rata-rata F1-macro: {cv_f1.mean()*100:.2f}% ± {cv_f1.std()*100:.2f}%")

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
folds = [f"Fold {i+1}" for i in range(5)]
for ax, scores, label, color in zip(
        axes,
        [cv_acc, cv_f1],
        ['Akurasi', 'F1-macro'],
        ['#3498DB', '#E74C3C']):
    bars = ax.bar(folds, scores * 100, color=color, edgecolor='white', width=0.5)
    ax.bar_label(bars, fmt='%.1f%%', padding=3, fontsize=9)
    ax.axhline(scores.mean() * 100, linestyle='--', color='gray',
               alpha=0.7, label=f'Rata-rata: {scores.mean()*100:.1f}%')
    ax.set_ylim(0, 115)
    ax.set_title(f"{label} per Fold (Training Post-SMOTE)", fontweight='bold')
    ax.set_ylabel(label)
    ax.legend(fontsize=9)

plt.suptitle("Validasi Silang 5-Fold XGBoost (Konsistensi Training)", fontsize=13)
plt.tight_layout()
plt.savefig("cross_validation_results.png", dpi=150, bbox_inches='tight')
plt.show()

"""CONFUSION MATRIX"""

cm      = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
cm_norm = confusion_matrix(y_test, y_pred, labels=[0, 1, 2], normalize='true')

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

disp1 = ConfusionMatrixDisplay(confusion_matrix=cm,
                                display_labels=LABEL_NAMES)
disp1.plot(ax=axes[0], cmap='Blues', colorbar=False)
axes[0].set_title("Confusion Matrix (Absolut)", fontweight='bold')
axes[0].set_xlabel("Prediksi")
axes[0].set_ylabel("Aktual")

disp2 = ConfusionMatrixDisplay(confusion_matrix=cm_norm,
                                display_labels=LABEL_NAMES)
disp2.plot(ax=axes[1], cmap='Blues', colorbar=False)
axes[1].set_title("Confusion Matrix (% per Kelas Aktual)", fontweight='bold')
axes[1].set_xlabel("Prediksi")
axes[1].set_ylabel("Aktual")
for text in axes[1].texts:
    try:
        val = float(text.get_text())
        text.set_text(f"{val * 100:.1f}%")
    except ValueError:
        pass

plt.suptitle("Confusion Matrix XGBoost — Data Uji (2024)", fontsize=13)
plt.tight_layout()
plt.savefig("confusion_matrix_xgboost.png", dpi=150, bbox_inches='tight')
plt.show()

"""FEATURE IMPORTANCE"""

def get_importance_named(booster, feat_names, itype):
    raw = booster.get_score(importance_type=itype)
    named = {}
    for k, v in raw.items():
        idx = int(k[1:])
        if idx < len(feat_names):
            named[feat_names[idx]] = v
    return [named.get(f, 0.0) for f in feat_names]

booster = model.get_booster()
fi_all = pd.DataFrame({
    'feature': features,
    'weight' : get_importance_named(booster, features, 'weight'),
    'gain'   : get_importance_named(booster, features, 'gain'),
    'cover'  : get_importance_named(booster, features, 'cover'),
})

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for ax, itype in zip(axes, ['weight', 'gain', 'cover']):
    fi_sorted = fi_all.sort_values(itype, ascending=True)
    max_val   = fi_sorted[itype].max()
    bars = ax.barh(fi_sorted['feature'], fi_sorted[itype],
                   color='#3498DB', edgecolor='white')
    ax.bar_label(bars, fmt='%.3f', padding=3, fontsize=8)
    ax.set_title(f"Feature Importance\n({itype.capitalize()})", fontweight='bold')
    ax.set_xlabel('Skor')
    ax.set_xlim(0, max_val * 1.30 if max_val > 0 else 1)

plt.suptitle("Feature Importance XGBoost (3 Metrik)", fontsize=13)
plt.tight_layout()
plt.savefig("feature_importance_xgboost.png", dpi=150, bbox_inches='tight')
plt.show()

print("\n=== FEATURE IMPORTANCE (GAIN — paling informatif) ===")
print(fi_all.sort_values('gain', ascending=False).to_string(index=False))

"""PERBANDINGAN DENGAN MODEL LAIN"""

other_models = {
    "Random Forest"      : RandomForestClassifier(
        n_estimators=200, max_depth=10,
        class_weight='balanced', random_state=42),
    "SVM"                : SVC(
        kernel='rbf', C=1, gamma='scale',
        probability=True, class_weight='balanced', random_state=42),
    "Logistic Regression": LogisticRegression(
        C=1, penalty='l2', class_weight='balanced',
        max_iter=1000, random_state=42),
}

comparison_results = []
for name, clf in other_models.items():
    clf.fit(X_train_res, y_train_res)
    yp    = clf.predict(X_test_scaled)
    acc_c = accuracy_score(y_test, yp)
    f1_c  = f1_score(y_test, yp, average='macro', zero_division=0)
    comparison_results.append([name, round(acc_c, 4), round(f1_c, 4)])
    print(f"{name:25s}: Akurasi = {acc_c*100:.2f}%  |  Macro F1 = {f1_c*100:.2f}%")

comparison_results.append(["XGBoost (Proposed)",
                            round(acc_xgb, 4), round(f1_macro_xgb, 4)])
df_cmp = pd.DataFrame(comparison_results,
                       columns=["Model", "Akurasi", "Macro F1"])
df_cmp = df_cmp.sort_values("Akurasi", ascending=False).reset_index(drop=True)

print("\nTabel Perbandingan Model (diurutkan Akurasi):")
print(df_cmp.to_string(index=False))

fig, ax = plt.subplots(figsize=(10, 5))
x  = np.arange(len(df_cmp))
w  = 0.35
b1 = ax.bar(x - w/2, df_cmp['Akurasi'],  w, label='Akurasi',  color='#3498DB')
b2 = ax.bar(x + w/2, df_cmp['Macro F1'], w, label='Macro F1', color='#E74C3C')
ax.bar_label(b1, fmt='%.3f', padding=3, fontsize=9)
ax.bar_label(b2, fmt='%.3f', padding=3, fontsize=9)
ax.set_xticks(x)
ax.set_xticklabels(df_cmp['Model'], rotation=15, ha='right')
ax.set_ylim(0, 1.20)
ax.set_ylabel("Skor")
ax.set_title("Perbandingan Performa Model ML", fontweight='bold')
ax.axhline(0.8, linestyle='--', color='gray', alpha=0.5, label='Batas 80%')
ax.legend()
plt.tight_layout()
plt.savefig("model_comparison.png", dpi=150, bbox_inches='tight')
plt.show()

"""SHAP ANALYSIS"""

try:
    X_shap = pd.DataFrame(X_test_scaled, columns=features)

    explainer = shap.Explainer(model, X_shap)
    shap_exp  = explainer(X_shap)

    sv = shap_exp.values
    print(f"SHAP values shape: {sv.shape}")

    if sv.ndim == 3:
        shap_list = [sv[:, :, i] for i in range(sv.shape[2])]
    elif sv.ndim == 2:
        shap_list = [sv]
    else:
        raise ValueError(f"Format SHAP tidak dikenal: shape={sv.shape}")

    for i, class_name in enumerate(LABEL_NAMES):
        if i >= len(shap_list):
            break
        mean_abs = np.abs(shap_list[i]).mean(axis=0)
        fi_shap  = pd.DataFrame({'feature': features, 'shap': mean_abs})
        fi_shap  = fi_shap.sort_values('shap', ascending=True)

        plt.figure(figsize=(9, 5))
        bars = plt.barh(fi_shap['feature'], fi_shap['shap'],
                        color=COLOR_RISIKO[i], edgecolor='white')
        plt.bar_label(bars, fmt='%.4f', padding=3, fontsize=9)
        plt.xlabel('Mean |SHAP value|')
        plt.title(f"SHAP Feature Importance — Kelas {class_name}", fontweight='bold')
        plt.xlim(0, fi_shap['shap'].max() * 1.25)
        plt.tight_layout()
        plt.savefig(f"shap_bar_{class_name}.png", dpi=150, bbox_inches='tight')
        plt.show()
        print(f"SHAP kelas {class_name}:\n{fi_shap.sort_values('shap', ascending=False).to_string(index=False)}\n")

    if len(shap_list) >= 3:
        shap_exp_tinggi = shap.Explanation(
            values     = shap_list[2],
            base_values= explainer.expected_value[2] if hasattr(explainer.expected_value, '__len__') else explainer.expected_value,
            data       = X_shap.values,
            feature_names=features
        )
        plt.figure(figsize=(9, 5))
        shap.plots.beeswarm(shap_exp_tinggi, show=False, max_display=10)
        plt.title("SHAP Beeswarm — Kelas Risiko Tinggi", fontweight='bold')
        plt.tight_layout()
        plt.savefig("shap_beeswarm_tinggi.png", dpi=150, bbox_inches='tight')
        plt.show()

except Exception as e:
    print(f"SHAP error: {e}")
    import traceback; traceback.print_exc()
    print("\nFallback: plot dari feature_importances_")
    fi_fb = pd.DataFrame({'feature': features,
                          'importance': model.feature_importances_}
                        ).sort_values('importance', ascending=True)
    plt.figure(figsize=(9, 5))
    bars = plt.barh(fi_fb['feature'], fi_fb['importance'],
                    color='#e74c3c', edgecolor='white')
    plt.bar_label(bars, fmt='%.4f', padding=3, fontsize=9)
    plt.xlabel('Feature Importance (XGBoost built-in)')
    plt.title("Feature Importance Fallback", fontweight='bold')
    plt.tight_layout()
    plt.savefig("shap_fallback.png", dpi=150, bbox_inches='tight')
    plt.show()

"""SIMPAN"""

joblib.dump(model,        "model_xgboost_tbc.pkl")
joblib.dump(scaler,       "scaler_minmax.pkl")
joblib.dump(P33,          "threshold_p33.pkl")
joblib.dump(P66,          "threshold_p66.pkl")
joblib.dump(best_t0,      "threshold_t0.pkl")
joblib.dump(best_t_high,  "threshold_t_high.pkl")
joblib.dump(features,     "features.pkl")
joblib.dump(df,           "data_processed.pkl")